# Generated by Django 2.2.7 on 2019-11-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_description',
            field=models.CharField(default='Description placeholder', max_length=2000),
            preserve_default=False,
        ),
    ]
