# Generated by Django 2.2.7 on 2019-11-17 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_voters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='polls_close',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='polls close'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='polls_open',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='polls open'),
            preserve_default=False,
        ),
    ]
